### ISSUE TITLE
Teams, etc, not saving to DB

### ISSUE THREAD

**Issue by minax0v** [sreilly64/Showdown-Team-Scraper#3]
Hi! I'm not sure if i have everything set up correctly, the script runs but nothing is being saved to the DB.

Here are my env variables and a picture of the DB.

![image](https://user-images.githubusercontent.com/131496333/233849202-ec4f05e7-9d93-4aae-b3e5-252e026dfbcc.png)
![image](https://user-images.githubusercontent.com/131496333/233849213-14cb6d18-e044-45ae-a199-0e576c3931b8.png)
![image](https://user-images.githubusercontent.com/131496333/233849295-065144f7-98bb-43e7-8c12-a3c6a51ef963.png)

output of the script running: 
![image](https://user-images.githubusercontent.com/131496333/233849309-d9b234e3-7815-4074-8072-542116daf2a8.png)

**Comment by sreilly64** [comment]
It looks like your database name in MongoDB Compass is "pokemon" but in your environment variables it is "Pokemon". When I did this in my local I got an error saying the casing didn't match. Are there any exceptions being show in the console?

**Comment by sreilly64** [comment]
Closing this issue due to lack of response.
